---
# Installs k0s
# Setup kubectl config for user 'kubectl_user', which in my case is 'dries'
# Creates a dir /srv/k8s for local storage
# Adds nginx-ingress, with a default backend

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - k0s_version is defined
      - k0s_version | length > 0
      - k0s_arch is defined
      - k0s_arch | length > 0
      - kubectl_user is defined
      - kubectl_user | length > 0
      - server_fqdn is defined
      - server_fqdn | length > 0
      - nginx_ingress_default_backend_image is defined # nginx:stable-alpine
      - nginx_ingress_default_backend_image | length > 0

- name: Print variables
  debug:
    msg: "k0s_version: {{ k0s_version }}, k0s_arch: {{ k0s_arch }}"

- name: Download k0s binary
  get_url:
    url: https://github.com/k0sproject/k0s/releases/download/{{ k0s_version | urlencode }}/k0s-{{ k0s_version }}-{{ k0s_arch }}
    dest: /usr/local/bin/k0s
    mode: '0755'

- name: Initialize k0s as a controller
  ansible.builtin.command: /usr/local/bin/k0s install controller --single --enable-worker --no-taints
  args:
    creates: /etc/systemd/system/k0scontroller.service

- name: Start and enable k0s service
  systemd:
    name: k0scontroller
    enabled: true
    state: started

- name: Verify k0s version
  ansible.builtin.command: /usr/local/bin/k0s version
  register: k0s_version_output

- name: Show k0s version
  debug:
    msg: "k0s version output: {{ k0s_version_output.stdout_lines }}"

- name: Verify k0s status
  ansible.builtin.command: /usr/local/bin/k0s status
  register: k0s_status_output

- name: Show k0s version
  debug:
    msg: "k0s status output: {{ k0s_status_output.stdout_lines }}"

- name: Ensure kube config dir exists
  file:
    path: /home/{{ kubectl_user }}/.kube
    owner: "{{ kubectl_user }}"
    group: "{{ kubectl_user }}"
    state: directory
    mode: '0750'

- name: Setup kube admin access config
  ansible.builtin.shell: "/usr/local/bin/k0s kubeconfig admin > /home/{{ kubectl_user }}/.kube/config"
  args:
    creates: /home/{{ kubectl_user }}/.kube/config

- name: dir for k8s local storage
  file:
    path: /srv/k8s
    owner: root
    state: directory
    mode: '0755'

- name: Install kubernetes python package
  # very scary but I need it to run some k8s commands from ansible
  ansible.builtin.pip:
    name: kubernetes
    break_system_packages: true

- name: Deploy nginx ingress namespace
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deploy-nginx-ingress-1-namespace.yaml') }}"
    kubeconfig: /home/{{ kubectl_user }}/.kube/config

- name: Check if the nginx ingress namespace was created in k0s
  kubernetes.core.k8s_info:
    kind: Namespace
    name: ingress-nginx
    kubeconfig: /home/{{ kubectl_user }}/.kube/config
  register: ingress_nginx_namespace
  until: "'ingress-nginx' in ingress_nginx_namespace.resources | map(attribute='metadata.name') | list"
  retries: 1

- name: Deploy default backend
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'default-backend.yaml.j2') }}"
    kubeconfig: /home/{{ kubectl_user }}/.kube/config

- name: Deploy nginx ingress RBAC
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deploy-nginx-ingress-2-rbac.yaml') }}"
    kubeconfig: /home/{{ kubectl_user }}/.kube/config

- name: Check if the nginx ingress roles and bindings were created in k0s
  kubernetes.core.k8s_info:
    kind: ClusterRoleBinding
    name: ingress-nginx-admission
    kubeconfig: /home/{{ kubectl_user }}/.kube/config
  register: ingress_nginx_admission_crb
  until: "'ingress-nginx-admission' in ingress_nginx_admission_crb.resources | map(attribute='metadata.name') | list"
  retries: 1

- name: Deploy nginx ingress configmap
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deploy-nginx-ingress-3-configmap.yaml') }}"
    kubeconfig: /home/{{ kubectl_user }}/.kube/config

- name: Check if the nginx ingress config map was created in k0s
  kubernetes.core.k8s_info:
    kind: ConfigMap
    name: ingress-nginx-controller
    namespace: ingress-nginx
    kubeconfig: /home/{{ kubectl_user }}/.kube/config
  register: ingress_nginx_configmap
  until: "'ingress-nginx-controller' in ingress_nginx_configmap.resources | map(attribute='metadata.name') | list"
  retries: 1

- name: Deploy nginx ingress services
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deploy-nginx-ingress-4-services.yaml') }}"
    kubeconfig: /home/{{ kubectl_user }}/.kube/config

- name: Deploy nginx ingress deployment
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deploy-nginx-ingress-5-daemonsets.yaml') }}"
    kubeconfig: /home/{{ kubectl_user }}/.kube/config

- name: Check if the nginx ingress controller pod was created in k0s
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: ingress-nginx
    label_selectors:
      - app.kubernetes.io/component = controller
      - app.kubernetes.io/name = ingress-nginx
    kubeconfig: /home/{{ kubectl_user }}/.kube/config
  register: ingress_nginx_controller_pod
  # fails if no pod found
  until: "'ingress-nginx' in ingress_nginx_controller_pod.resources | map(attribute='metadata.namespace') | list"
  retries: 1

- name: Deploy nginx ingress jobs
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deploy-nginx-ingress-6-jobs.yaml') }}"
    kubeconfig: /home/{{ kubectl_user }}/.kube/config

- name: Deploy nginx ingress ingressclass
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deploy-nginx-ingress-7-ingressclass.yaml') }}"
    kubeconfig: /home/{{ kubectl_user }}/.kube/config

- name: Deploy nginx ingress webhook
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deploy-nginx-ingress-8-webhook.yaml') }}"
    kubeconfig: /home/{{ kubectl_user }}/.kube/config


